#!/bin/bash
until false  #Создаем безконечный цыкл
 do
p_file=`mktemp 2>/dev/null` #Создаем временный файл и записываем путь к нему в переменную
trap "rm -f $p_file" 0 1 2 5 15 #Удаляем файл если получен один из сигналов
#Запускаем диалог
dialog  --title "Your password" \
        --clear \
        --insecure \
        --passwordbox "Enter the password:" 10 30 2> $p_file #Запись в файл



click=$?
#DATE=`/bin/date '+%d.%m.%Y'`
DATE=`/bin/date '+%H:%M'`
case $click in
  0)
    if [ "$(cat $p_file)" = $DATE ]
    then sh tasks 
    break 
    fi
    ;;
   1) break;;
255) break;;
esac
done 
   
